### ISSUE TITLE
Make it faster

### ISSUE THREAD

**Issue by stacho** [polygon-io/ui-swagger#33]
Is there anyway to improve the performance to make the docs faster? Takes quite a while to load, and also takes a decent amount of time to navigate between endpoints. If possible we'd want it to feel instant.

**Comment by qrpike** [comment]
Current page speed:
- Mobile: 3
- Desktop: 30

**Comment by qrpike** [comment]
The changes did improve the score:
- Mobile: 6
- Desktop: 42
