### ISSUE TITLE
Wrong Logo used in Nav Bar

### ISSUE THREAD

**Issue by jrbell19** [polygon-io/ui-swagger#77]
We had the issue on the main page, but I guess it wasn't resolved here. If you zoom in while on the docs you can see the logo is all kinds of messed up. See below

![image](https://user-images.githubusercontent.com/53952508/88971751-78a6cc00-d282-11ea-8b78-6d367b23545e.png)

**Comment by teambailey** [comment]
@jrbell19 This has been fixed
